apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaBridge
metadata:
  name: cloudgeeks-ca-bridge
  namespace: kafka
spec:
  replicas: 3
  bootstrapServers: cloudgeeks-ca-kafka-kafka-bootstrap:9092
  http:
    port: 8080


# ---> Simply access the POD directly ---> Setup via Deployment
################################################################################################
# kubectl expose deployment cloudgeeks-ca-bridge-bridge --type=NodePort  --protocol TCP --port 80 --target-port 8080 --overrides='{ "apiVersion": "v1", "metadata": {"annotations": { "service.beta.kubernetes.io/aws-load-balancer-type":"nlb-ip" } } }' --name=cloudgeeks-ca-bridge-exposed  -n kafka
###############################################################################################


# Different Version of Srimzi Kafka Bridge 

#############################################################################
# Different Strimzi kafka bridge
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
# Simple do ------------------------------>  kubectl edit deployment/cloudgeeks-ca-bridge-bridge -n kafka
##############################################################################
# kubectl rollout status deployment/cloudgeeks-ca-bridge-bridge -n kafka

# kubectl expose deployment cloudgeeks-ca-bridge-bridge --type=NodePort  --protocol TCP --port 80 --target-port 8080 --name=cloudgeeks-ca-bridge-exposed  -n kafka

# kubectl expose deployment cloudgeeks-ca-bridge-bridge --type=NodePort --name=cloudgeeks-kafka-exposed -n kafka











# https://hub.docker.com/r/strimzi/kafka-bridge
# Update the image of existing deployment # https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

# kubectl set image deployment/nginx-deployment nginx=nginx:1.16.1 --record


#  Container in a pod
#  kubectl get pods POD_NAME_HERE -o jsonpath='{.spec.containers[*].name}'
# ----> kubectl set image deployment/cloudgeeks-ca-bridge-bridge cloudgeeks-ca-bridge-bridge=strimzi/kafka-bridge:0.18.0 -n kafka --record



# List
# https://kubernetes.io/docs/tasks/access-application-cluster/list-all-running-container-images/
# https://stackoverflow.com/questions/33924198/how-do-you-cleanly-list-all-the-containers-in-a-kubernetes-pod
#

#  Container in a pod
#  kubectl get pods POD_NAME_HERE -o jsonpath='{.spec.containers[*].name}'
#
#  kubectl get pods cloudgeeks-ca-bridge-bridge-5694dc7dc5-8rpd2 -o jsonpath='{.spec.containers[*].name}' -n kafka
#
#  # Shell
#  # https://kubernetes.io/docs/tasks/debug-application-cluster/get-shell-running-container/
#  In a container which is in a POD
#
#  kubectl exec -it -n kafka cloudgeeks-ca-bridge-bridge-5694dc7dc5-8rpd2 --container cloudgeeks-ca-bridge-bridge -- /bin/bash



# https://github.com/kubernetes/kubectl/issues/826    

# https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html

# https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/    

# https://cloud.google.com/kubernetes-engine/docs/how-to/exposing-apps

# kubectl.exe expose deployment cloudgeeks-ca-bridge-bridge --type=NodePort --name=cloudgeeks-ca-bridge-bridge-service-cloudgeeks-ca -n kafka

# kubectl expose deployment cloudgeeks-ca-bridge-bridge --type=NodePort  --protocol TCP --port 80 --target-port 8080 --overrides='{ "apiVersion": "v1", "metadata": {"annotations": { "service.beta.kubernetes.io/aws-load-balancer-type":"nlb-ip" } } }' --name=cloudgeeks-ca-bridge-nlb  -n kafka

# "metadata": {"annotations": { "service.beta.kubernetes.io/aws-load-balancer-type":"nlb-ip" } }

# --overrides='{ "apiVersion": "v1", "metadata": {"annotations": { "service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip" } } }'
