#!/bin/bash
#Purpose: AWS-CLI
#OS: Centos-7

sudo yum update -y

sudo curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"

sudo yum install unzip -y > /dev/null

sudo unzip awscli-bundle.zip > /dev/null

mkdir -p ~/bin

sudo ./awscli-bundle/install -i ~/bin



#For Centos-7 root user only
# https://www.rosehosting.com/blog/how-to-install-python-3-6-4-on-centos-7/

#Step 1: Open a Terminal and add the repository to your Yum install.
sudo yum install -y https://centos7.iuscommunity.org/ius-release.rpm
#Step 2: Update Yum to finish adding the repository.
sudo yum update
#Step 3: Download and install Python.
#This will not only install Python – but it will also install pip to help you with installing add-ons.

sudo yum install -y python36u python36u-libs python36u-devel python36u-pip
#Once these commands are executed, simply check if the correct version of Python has been installed by executing the following command:

python3.6 -V
#You have now finished installing Python 3.6.4 on your CentOS 7 machine, as well as installing a native Python package management tool called pip.
cp ~/bin/bin/aws /usr/local/bin > /dev/null
cp ~/bin/bin/aws /usr/bin

aws --version

#END

# https://www.rosehosting.com/blog/how-to-install-python-3-6-4-on-centos-7/
#  python3.6 -m pip install --user boto3
 
