#!/bin/bash
# OS: Ubuntu
# DevOps: cloudgeeks.ca
# https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/download-cloudwatch-agent-commandline.html


export REGION=us-east-1

#-----------
# App1 logs
#-----------
export APPLICATION_LOGS=/var/log/cloudgeeksapp1.log
export LOG_GROUP_NAME=cloudgeeks-app1
export LOG_STREAM_NAME=cloudgeeks-app1-stream

#-----------
# App2 logs
#-----------
export APPLICATION_LOGS2=/var/log/cloudgeeksapp2.log
export LOG_GROUP_NAME2=cloudgeeks-app2
export LOG_STREAM_NAME2=cloudgeeks-app1-stream

#---------------------------
# Cloudwatch Ubuntu Package
#---------------------------
curl -LO -# https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb

sudo dpkg -i -E ./amazon-cloudwatch-agent.deb



# CloudWatch Agent Configuration

cat <<EOF > /opt/aws/amazon-cloudwatch-agent/bin/config.json
{
     "agent": {
         "run_as_user": "root"
     },
     "logs": {
         "logs_collected": {
             "files": {
                 "collect_list": [
                     {
                         "file_path": "${APPLICATION_LOGS}",
                         "log_group_name": "${LOG_GROUP_NAME}",
                         "log_stream_name": "${LOG_STREAM_NAME}"
                     },

                       {
                          "file_path": "${APPLICATION_LOGS2}",
                          "log_group_name": "${LOG_GROUP_NAME2}",
                          "log_stream_name": "${LOG_STREAM_NAME2}"
                        }
                 ]
             }
         }
     }


 }

EOF

#--------------------------
# CloudWatch Service Start
#---------------------------
/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json -s

#----------------------------
# CloudWatch Service Enable
#----------------------------
systemctl enable amazon-cloudwatch-agent.service


# End
