#!/bin/bash
#Purpose: ALB Ingress Setup
#Maintainer: Muhammad Asim <quickbooks2018@gmail.com>

VPC_ID=`terraform output vpc-id`
################################
ACCOUNT_ID="YOURAWSACCOUNT"
################################
REGION="us-east-1"
CLUSTER_NAME="cloudgeeks-eks"

# Update Me 
##############################################################################
Policy_Arn="arn:aws:iam::${ACCOUNT_ID}:policy/ALBIngressControllerIAMPolicy"
##############################################################################


# Create an IAM OIDC provider and associate it with your cluster. If you don't have eksctl version 0.14.0 or later installed, complete the instructions in Installing or Upgrading eksctl to install or upgrade it. You can check your installed version with eksctl version.

eksctl utils associate-iam-oidc-provider \
    --region $REGION \
    --cluster $CLUSTER_NAME \
    --approve


curl -# -LO https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/master/docs/examples/iam-policy.json

sleep 10

aws iam create-policy --policy-name ALBIngressControllerIAMPolicy --policy-document file://iam-policy.json

kubectl create serviceaccount alb-ingress-controller -n kube-system

kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/master/docs/examples/rbac-role.yaml


eksctl create iamserviceaccount \
    --region $REGION \
    --name alb-ingress-controller \
    --namespace kube-system \
    --cluster $CLUSTER_NAME \
    --attach-policy-arn $POLICY_ARN \
    --override-existing-serviceaccounts \
    --approve

# Deploy the ALB Ingress Controller with the following command.

kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/master/docs/examples/alb-ingress-controller.yaml


kubectl describe sa alb-ingress-controller -n kube-system

echo -e "\nOpen the ALB Ingress Controller deployment manifest for editing with the following command\n"

echo -e "\nkubectl edit deployment.apps/alb-ingress-controller -n kube-system\n"

echo -e "\nThe line number is 41, at the  end of line press ENTER\n"

echo -e "- --cluster-name=$CLUSTER_NAME"
echo -e "- --aws-vpc-id=$VPC_ID"
echo -e "- --aws-region=$REGION"



echo -e "\n If ALB is not setup check the logs with mentioned below commands \n"


echo -e "\n    kubectl logs -n kube-system   deployment.apps/alb-ingress-controller   \n"


echo -e "\n Confirm that the ALB Ingress Controller is running with the following command\n"

echo -e "\n kubectl get pods -n kube-system \n"


#END



# https://aws.amazon.com/premiumsupport/knowledge-center/eks-alb-ingress-controller-setup/

# ALB Ingress EKS Sample app

kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/master/docs/examples/2048/2048-namespace.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/master/docs/examples/2048/2048-deployment.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/master/docs/examples/2048/2048-service.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/master/docs/examples/2048/2048-ingress.yaml


# Ingress ---> https://aws.amazon.com/premiumsupport/knowledge-center/eks-alb-ingress-controller-fargate/
# Ingress ---> https://github.com/quickbooks2018/aws/blob/master/eks  ---> SEARCH Annotations or watch video ----> https://www.youtube.com/watch?v=UHpIxQSAM-A&t=94s

kubectl get ingress/2048-ingress -n 2048-game

kubectl logs -n kube-system deployment.apps/alb-ingress-controller

kubectl delete -f https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/master/docs/examples/2048/2048-namespace.yaml


_____________________________________________________________________________________________________________________________________________________________________________
# Helm3

#!/bin/bash
# Purpose: alb ingress setup via helm3
# https://aws.amazon.com/premiumsupport/knowledge-center/eks-alb-ingress-controller-fargate/
# https://github.com/aws/eks-charts
# https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller

EksCluster="cloudgeeksca-cluster-eks"
Region="us-east-1"
VpcId=`aws ec2 describe-vpcs --region us-east-1 --filters Name=tag:Name,Values=cloudgeeksca-cluster-eks --query "Vpcs[].VpcId" | grep -i vpc | cut -f1`

# Install the AWS Load Balancer Controller using Helm

helm version --short

helm repo add eks https://aws.github.io/eks-charts

# To install the TargetGroupBinding custom resource definitions (CRDs), run the following command:


kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"


# To install the Helm chart, run the following command:

helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName="${EksCluster}"



# END

-------------------------------------------------------------------------------------------------------------------------------------------


EksCluster="cloudgeeks-ca-eks"
Region="us-east-1"
VpcId=`aws ec2 describe-vpcs --region us-east-1 --filters Name=tag:eksctl.cluster.k8s.io/v1alpha1/cluster-name,Values=cloudgeeks-ca-eks --query "Vpcs[].VpcId" | grep -i vpc | cut -f1`
