#!/bin/bash

curl -# -LO https://get.helm.sh/helm-v3.5.3-linux-amd64.tar.gz
tar -xzvf helm-v3.5.3-linux-amd64.tar.gz
mv linux-amd64/helm /usr/bin/helm
rm -rf helm-v3.5.3-linux-amd64.tar.gz && rm -rf linux-amd64

# End
