#!/bin/bash

##########
# Packages
##########

yum install -y git jq tmux dos2unix curl wget

###########
# Terraform
###########
yum install -y yum-utils
yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
yum -y install terraform

############
# Terragrunt
############
curl -# -LO https://github.com/gruntwork-io/terragrunt/releases/download/v0.35.16/terragrunt_linux_amd64

mv terragrunt_linux_amd64 terragrunt && chmod +x terragrunt && mv terragrunt /usr/bin/terragrunt

#########
# Kubectl
#########
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
chmod +x ./kubectl
mv ./kubectl /usr/bin/kubectl


# End
