
AWSTemplateFormatVersion: 2010-09-09

Resources:
  TransitGateway:
    Type: "AWS::EC2::TransitGateway"
    Properties:
      Description: "TGW Route Integration Test"
      AmazonSideAsn: 64512
      AutoAcceptSharedAttachments: "enable"
      DefaultRouteTableAssociation: "enable"
      DefaultRouteTablePropagation: "enable"
      DnsSupport: "enable"
      VpnEcmpSupport: "enable"
      Tags:
      - Key: Application
        Value: !Ref 'AWS::StackId'
      - Key: Name
        Value: cloudgeeksca-cf-tgw-us-east-1
      

Outputs:
  TransitGateway:
    Description: Transit Gateway Name
    Value: !Ref TransitGateway
