---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: goapp
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: goapp
  labels:
    name: goapp
spec:
  storageClassName: "goapp"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi